extensions:
  file_storage:
    directory: /var/lib/otelcol

receivers:
  filelog/docker:
    include: [/var/log/docker/*/*-json.log]
    start_at: end
    include_file_path: true
    storage: file_storage
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0s
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout_type: gotime
          layout: '2006-01-02T15:04:05.999999999Z07:00'
      - type: regex_parser
        parse_from: attributes["log.file.path"]
        regex: '^/var/log/docker/(?P<container_id>[^/]+)/'
      - type: move
        from: attributes.container_id
        to: resource["container.id"]
      - type: move
        from: attributes.log
        to: body

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 384
    spike_limit_mib: 64
  resource:
    attributes:
      - key: service.namespace
        value: influence
        action: upsert
      - key: deployment.environment.name
        value: ${env:OTEL_ENVIRONMENT}
        action: upsert
      - key: host.name
        value: ${env:OTEL_HOST_NAME}
        action: upsert
  transform/service:
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["service.name"], log.attributes["attrs"]["com.docker.compose.service"]) where IsMap(log.attributes["attrs"]) and log.attributes["attrs"]["com.docker.compose.service"] != nil
  batch:
    timeout: 5s
    send_batch_size: 512
    send_batch_max_size: 1024

exporters:
  otlphttp:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
    compression: gzip
    headers:
      apikey: ${file:/run/secrets/mezmo_ingestion_key}
    sending_queue:
      storage: file_storage
      queue_size: 1000
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0s

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog/docker]
      processors: [memory_limiter, resource, transform/service, batch]
      exporters: [otlphttp]
